/* 
 * Atlas.Auth API
 *
 * Authentication/authorization service
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Atlas.Auth.Client.Client;
using Atlas.Auth.Client.Model;

namespace Atlas.Auth.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILoginApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Authentication with username and password
        /// </summary>
        /// <remarks>
        /// Sample request:                    POST /Login      {         \&quot;Username\&quot;: \&quot;username@example.com\&quot;,         \&quot;Password\&quot;: \&quot;password\&quot;      }
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional)</param>
        /// <returns>LoginMessageModel</returns>
        LoginMessageModel ApiV1LoginPost (LoginModel model = null);

        /// <summary>
        /// Authentication with username and password
        /// </summary>
        /// <remarks>
        /// Sample request:                    POST /Login      {         \&quot;Username\&quot;: \&quot;username@example.com\&quot;,         \&quot;Password\&quot;: \&quot;password\&quot;      }
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional)</param>
        /// <returns>ApiResponse of LoginMessageModel</returns>
        ApiResponse<LoginMessageModel> ApiV1LoginPostWithHttpInfo (LoginModel model = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Authentication with username and password
        /// </summary>
        /// <remarks>
        /// Sample request:                    POST /Login      {         \&quot;Username\&quot;: \&quot;username@example.com\&quot;,         \&quot;Password\&quot;: \&quot;password\&quot;      }
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional)</param>
        /// <returns>Task of LoginMessageModel</returns>
        System.Threading.Tasks.Task<LoginMessageModel> ApiV1LoginPostAsync (LoginModel model = null);

        /// <summary>
        /// Authentication with username and password
        /// </summary>
        /// <remarks>
        /// Sample request:                    POST /Login      {         \&quot;Username\&quot;: \&quot;username@example.com\&quot;,         \&quot;Password\&quot;: \&quot;password\&quot;      }
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional)</param>
        /// <returns>Task of ApiResponse (LoginMessageModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<LoginMessageModel>> ApiV1LoginPostAsyncWithHttpInfo (LoginModel model = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LoginApi : ILoginApi
    {
        private Atlas.Auth.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LoginApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LoginApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Atlas.Auth.Client.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LoginApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LoginApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Atlas.Auth.Client.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Atlas.Auth.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Authentication with username and password Sample request:                    POST /Login      {         \&quot;Username\&quot;: \&quot;username@example.com\&quot;,         \&quot;Password\&quot;: \&quot;password\&quot;      }
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional)</param>
        /// <returns>LoginMessageModel</returns>
        public LoginMessageModel ApiV1LoginPost (LoginModel model = null)
        {
             ApiResponse<LoginMessageModel> localVarResponse = ApiV1LoginPostWithHttpInfo(model);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Authentication with username and password Sample request:                    POST /Login      {         \&quot;Username\&quot;: \&quot;username@example.com\&quot;,         \&quot;Password\&quot;: \&quot;password\&quot;      }
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional)</param>
        /// <returns>ApiResponse of LoginMessageModel</returns>
        public ApiResponse< LoginMessageModel > ApiV1LoginPostWithHttpInfo (LoginModel model = null)
        {

            var localVarPath = "/api/v1/Login";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null && model.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(model); // http body (model) parameter
            }
            else
            {
                localVarPostBody = model; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1LoginPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LoginMessageModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LoginMessageModel) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LoginMessageModel)));
        }

        /// <summary>
        /// Authentication with username and password Sample request:                    POST /Login      {         \&quot;Username\&quot;: \&quot;username@example.com\&quot;,         \&quot;Password\&quot;: \&quot;password\&quot;      }
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional)</param>
        /// <returns>Task of LoginMessageModel</returns>
        public async System.Threading.Tasks.Task<LoginMessageModel> ApiV1LoginPostAsync (LoginModel model = null)
        {
             ApiResponse<LoginMessageModel> localVarResponse = await ApiV1LoginPostAsyncWithHttpInfo(model);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Authentication with username and password Sample request:                    POST /Login      {         \&quot;Username\&quot;: \&quot;username@example.com\&quot;,         \&quot;Password\&quot;: \&quot;password\&quot;      }
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional)</param>
        /// <returns>Task of ApiResponse (LoginMessageModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LoginMessageModel>> ApiV1LoginPostAsyncWithHttpInfo (LoginModel model = null)
        {

            var localVarPath = "/api/v1/Login";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null && model.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(model); // http body (model) parameter
            }
            else
            {
                localVarPostBody = model; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1LoginPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LoginMessageModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LoginMessageModel) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LoginMessageModel)));
        }

    }
}
