/* 
 * Atlas.Auth API
 *
 * Authentication/authorization service
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Atlas.Auth.Client.Client;
using Atlas.Auth.Client.Model;

namespace Atlas.Auth.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ILogoutApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Remove authentication
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>MessageModel</returns>
        MessageModel ApiV1LogoutPost ();

        /// <summary>
        /// Remove authentication
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of MessageModel</returns>
        ApiResponse<MessageModel> ApiV1LogoutPostWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Remove authentication
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of MessageModel</returns>
        System.Threading.Tasks.Task<MessageModel> ApiV1LogoutPostAsync ();

        /// <summary>
        /// Remove authentication
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (MessageModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<MessageModel>> ApiV1LogoutPostAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class LogoutApi : ILogoutApi
    {
        private Atlas.Auth.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="LogoutApi"/> class.
        /// </summary>
        /// <returns></returns>
        public LogoutApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Atlas.Auth.Client.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LogoutApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public LogoutApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Atlas.Auth.Client.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Atlas.Auth.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Remove authentication 
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>MessageModel</returns>
        public MessageModel ApiV1LogoutPost ()
        {
             ApiResponse<MessageModel> localVarResponse = ApiV1LogoutPostWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Remove authentication 
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of MessageModel</returns>
        public ApiResponse< MessageModel > ApiV1LogoutPostWithHttpInfo ()
        {

            var localVarPath = "/api/v1/Logout";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1LogoutPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MessageModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (MessageModel) Configuration.ApiClient.Deserialize(localVarResponse, typeof(MessageModel)));
        }

        /// <summary>
        /// Remove authentication 
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of MessageModel</returns>
        public async System.Threading.Tasks.Task<MessageModel> ApiV1LogoutPostAsync ()
        {
             ApiResponse<MessageModel> localVarResponse = await ApiV1LogoutPostAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Remove authentication 
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (MessageModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<MessageModel>> ApiV1LogoutPostAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/v1/Logout";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1LogoutPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<MessageModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (MessageModel) Configuration.ApiClient.Deserialize(localVarResponse, typeof(MessageModel)));
        }

    }
}
