/* 
 * Atlas.Auth API
 *
 * Authentication/authorization service
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Atlas.Auth.Client.Client;
using Atlas.Auth.Client.Model;

namespace Atlas.Auth.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUserApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get user info by token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <returns>PrincipalModel</returns>
        PrincipalModel ApiV1UserByTokenGet (string token);

        /// <summary>
        /// Get user info by token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <returns>ApiResponse of PrincipalModel</returns>
        ApiResponse<PrincipalModel> ApiV1UserByTokenGetWithHttpInfo (string token);
        /// <summary>
        /// Get user info for existed Auth cookies
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>PrincipalModel</returns>
        PrincipalModel ApiV1UserGet ();

        /// <summary>
        /// Get user info for existed Auth cookies
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of PrincipalModel</returns>
        ApiResponse<PrincipalModel> ApiV1UserGetWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get user info by token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <returns>Task of PrincipalModel</returns>
        System.Threading.Tasks.Task<PrincipalModel> ApiV1UserByTokenGetAsync (string token);

        /// <summary>
        /// Get user info by token
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <returns>Task of ApiResponse (PrincipalModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<PrincipalModel>> ApiV1UserByTokenGetAsyncWithHttpInfo (string token);
        /// <summary>
        /// Get user info for existed Auth cookies
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of PrincipalModel</returns>
        System.Threading.Tasks.Task<PrincipalModel> ApiV1UserGetAsync ();

        /// <summary>
        /// Get user info for existed Auth cookies
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (PrincipalModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<PrincipalModel>> ApiV1UserGetAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UserApi : IUserApi
    {
        private Atlas.Auth.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UserApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UserApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = Atlas.Auth.Client.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UserApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UserApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Atlas.Auth.Client.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Atlas.Auth.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get user info by token 
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <returns>PrincipalModel</returns>
        public PrincipalModel ApiV1UserByTokenGet (string token)
        {
             ApiResponse<PrincipalModel> localVarResponse = ApiV1UserByTokenGetWithHttpInfo(token);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get user info by token 
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <returns>ApiResponse of PrincipalModel</returns>
        public ApiResponse< PrincipalModel > ApiV1UserByTokenGetWithHttpInfo (string token)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new ApiException(400, "Missing required parameter 'token' when calling UserApi->ApiV1UserByTokenGet");

            var localVarPath = "/api/v1/User/{token}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (token != null) localVarPathParams.Add("token", Configuration.ApiClient.ParameterToString(token)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1UserByTokenGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PrincipalModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PrincipalModel) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PrincipalModel)));
        }

        /// <summary>
        /// Get user info by token 
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <returns>Task of PrincipalModel</returns>
        public async System.Threading.Tasks.Task<PrincipalModel> ApiV1UserByTokenGetAsync (string token)
        {
             ApiResponse<PrincipalModel> localVarResponse = await ApiV1UserByTokenGetAsyncWithHttpInfo(token);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get user info by token 
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="token"></param>
        /// <returns>Task of ApiResponse (PrincipalModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PrincipalModel>> ApiV1UserByTokenGetAsyncWithHttpInfo (string token)
        {
            // verify the required parameter 'token' is set
            if (token == null)
                throw new ApiException(400, "Missing required parameter 'token' when calling UserApi->ApiV1UserByTokenGet");

            var localVarPath = "/api/v1/User/{token}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (token != null) localVarPathParams.Add("token", Configuration.ApiClient.ParameterToString(token)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1UserByTokenGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PrincipalModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PrincipalModel) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PrincipalModel)));
        }

        /// <summary>
        /// Get user info for existed Auth cookies 
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>PrincipalModel</returns>
        public PrincipalModel ApiV1UserGet ()
        {
             ApiResponse<PrincipalModel> localVarResponse = ApiV1UserGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get user info for existed Auth cookies 
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of PrincipalModel</returns>
        public ApiResponse< PrincipalModel > ApiV1UserGetWithHttpInfo ()
        {

            var localVarPath = "/api/v1/User";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1UserGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PrincipalModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PrincipalModel) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PrincipalModel)));
        }

        /// <summary>
        /// Get user info for existed Auth cookies 
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of PrincipalModel</returns>
        public async System.Threading.Tasks.Task<PrincipalModel> ApiV1UserGetAsync ()
        {
             ApiResponse<PrincipalModel> localVarResponse = await ApiV1UserGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get user info for existed Auth cookies 
        /// </summary>
        /// <exception cref="Atlas.Auth.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (PrincipalModel)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PrincipalModel>> ApiV1UserGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/v1/User";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("ApiV1UserGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PrincipalModel>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (PrincipalModel) Configuration.ApiClient.Deserialize(localVarResponse, typeof(PrincipalModel)));
        }

    }
}
